### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by laurencefass** [Ismaestro/angular7-example-app#35]
### Bug Report or Feature Request (mark with an `x`)

- [x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

node->
v11.1.0

ng->
@angular-devkit/architect          0.10.4
@angular-devkit/build-angular      0.10.4
@angular-devkit/build-ng-packagr   0.10.4
@angular-devkit/build-optimizer    0.10.4
@angular-devkit/build-webpack      0.10.4
@angular-devkit/core               7.0.4
@angular-devkit/schematics         7.0.4
@angular/cli                       7.0.4
@angular/fire                      5.1.0
@angular/flex-layout               7.0.0-beta.19
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.4
@schematics/angular                7.0.4
@schematics/update                 0.10.4
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.19.1

### Repro steps.
install as per instructions on gh homepage.

### The log given by the failure.
 npm install

```
> grpc@1.13.1 install /app/ng7-example/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v67-linux-x64-musl.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.13.1 and node@11.1.0 (node-v67 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.13.1 and node@11.1.0 (node-v67 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gypgyp ERR! configure error
gyp  ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
ERR!gyp ERR! stack      at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
configure errorgyp
ERR! stackgyp     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack      at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gypERR!  stackERR! Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp stack      at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gypgyp  ERR!ERR! stack      at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gypstack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! ERR!  stackstack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp  ERR!ERR!  stackstack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp  ERR!ERR! stack      at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gypSystem Linux 4.9.0-7-amd64
 ERR!gyp stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR!  stackERR!     at FSReqCallback.oncomplete (fs.js:161:21)
gyp command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR!  cwdERR! /app/ng7-example/node_modules/grpc
gyp System  Linux 4.9.0-7-amd64
gypERR! node -v v11.1.0
gyp ERR!  ERR!node-gyp -v  v3.8.0
gypcommand "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR!  not ok
ERR! cwd /app/ng7-example/node_modules/grpc
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/ng7-example/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
node-pre-gyp ERR! System Linux 4.9.0-7-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/ng7-example/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /app/ng7-example/node_modules/grpc
node-pre-gyp ERR! node -v v11.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/app/ng7-example/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-musl --napi_version=3 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-07T14_10_39_944Z-debug.log
```

### Desired functionality.
error free install

**Comment by Ismaestro** [comment]
Downgrade your node version (11 is too high) and read [this](https://github.com/grpc/grpc-node/issues/594).

BR
